### ISSUE TITLE
Can't roll Skill checks

### ISSUE THREAD

**Issue by Firehouse-Games** [Saibot393/enhancedcombathud-yzecoriolis#1]
Skill checks are not working. I cant seam to prompt them.
also the critical injuries are not prompted when the character is dead.
![image](https://github.com/Saibot393/enhancedcombathud-yzecoriolis/assets/108539457/1b67ce1f-15f6-497d-bc9f-5079b274ec47)

**Comment by Saibot393** [comment]
I will look into it as soon as possible

**Comment by Saibot393** [comment]
The bug is now fixed with v1.3.1

**Comment by Firehouse-Games** [comment]
Thanks mate. I appreciate how quickly you jumped on the issue. However there is something else Which I'm about to post.
