### ISSUE TITLE
Weapon bonus and target Picker are not functioning.

### ISSUE THREAD

**Issue by Firehouse-Games** [Saibot393/enhancedcombathud-yzecoriolis#2]
Hey there, Hopefully I am not becoming to much of a Hinderance to your life lol. 
there two thing I would like to bring to your attention, when you have the time.

If I use a weapon to attack, it doesn't seam to keep into account any type of Weapon bonus related.

![image](https://github.com/Saibot393/enhancedcombathud-yzecoriolis/assets/108539457/a300764b-bc2b-46e8-ab23-ff8123fdfe2c)

Also, the "target Picker" function, is not working. Not sure if like that by design, or another bug.
![image](https://github.com/Saibot393/enhancedcombathud-yzecoriolis/assets/108539457/93d4c337-18dd-4a06-a0ca-fae4f6d6bb4b)

Hopefully I am not bothering you to much. Thanks Again, and have good new eve.

**Comment by Saibot393** [comment]
Don't worry about the reports. The weapon boni should now work with v1.3.2.
The target picker currently doesn't work across my Argon implementations, i will take care of that at a later time. In the mean time i will try to hide the option to prevent confusion.
