### ISSUE TITLE
Auto-Fire-Weapons lack checkbox for automatic fire

### ISSUE THREAD

**Issue by kagedansa** [Saibot393/enhancedcombathud-yzecoriolis#4]
![grafik](https://github.com/Saibot393/enhancedcombathud-yzecoriolis/assets/110729103/0e725885-1dd2-446c-a0e4-a891d675a2b8)

At the moment the checkbox for weapons with automatic fire is missing. (left image: using HUD, right image: using character-sheet)

**Comment by Saibot393** [comment]
Solved with v1.3.3
