### ISSUE TITLE
movementMax and movementUsed is shown with digits if canvas-scaling has digits.

### ISSUE THREAD

**Issue by kagedansa** [Saibot393/enhancedcombathud-yzecoriolis#5]
![grafik](https://github.com/Saibot393/enhancedcombathud-yzecoriolis/assets/110729103/8d58910c-34a8-4193-a94e-a842cf7675eb)

**Comment by Saibot393** [comment]
I have added rounding for these numbers with v1.3.3, probably not the best solution but the best i could think of for now.
