### ISSUE TITLE
german translation not working properly

### ISSUE THREAD

**Issue by kagedansa** [Saibot393/enhancedcombathud-yzecoriolis#6]
This error occurs because the de-lang file has not been adapted to the module.

Line 2
 `	"enhancedcombathud-mutant-year-zero" : {`

should bei changed to

`	"enhancedcombathud-yzecoriolis" : {`

If you like you can also change the Descriptions to

		"Descriptions" : {
			"Flee"						: "Siehe Coriolis Regelbuch S.??",
			"FirstAid"					: "Siehe Coriolis Regelbuch S.94",
			"Tinkering"					: "Siehe Coriolis Regelbuch S.83",
			"Reload"					: "Siehe Coriolis Regelbuch S.89",
			"TakeCover"					: "Siehe Coriolis Regelbuch S.93",
			"Duck"						: "Siehe Coriolis Regelbuch S.83",
			"StandUp"					: "Siehe Coriolis Regelbuch S.86",
			"DrawWeapon"				: "Siehe Coriolis Regelbuch S.83",
			"Parry"						: "Siehe Coriolis Regelbuch S.87",
			"Opportunity"				: "Siehe Coriolis Regelbuch S.87",
			"Overwatch"					: "Siehe Coriolis Regelbuch S.90",
			"Defend"					: "Siehe Coriolis Regelbuch S.87"
		},

**Comment by Saibot393** [comment]
Thank you, the bug fix and the page numbers are included in the new v1.3.4
